name: Deploy to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm install

      - name: Deploy through Load Balancer to BE-01
        uses: appleboy/ssh-action@master
        with:
          host: 42.96.41.26
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # SSH vào BE-01 và thực hiện deploy
            ssh be-01 '
              cd /srv/app/workspace-backend
              
              # Kiểm tra xem đã có git repo chưa
              if [ ! -d .git ]; then
                # Nếu chưa có git repo, clone mới
                rm -rf ./* 2>/dev/null || true
                rm -rf ./.* 2>/dev/null || true
                git clone https://github.com/Linh3694/workspace-backend.git .
              else
                # Nếu đã có git repo, fetch và reset
                git fetch origin
                git reset --hard origin/main
                git clean -fd
              fi
              
              # Cài đặt dependencies và chạy script
              npm install --production
              node scripts/addEmoji.js
              
              # Reload ứng dụng
              pm2 reload all
            '

      - name: Deploy through Load Balancer to BE-02
        uses: appleboy/ssh-action@master
        with:
          host: 42.96.41.26
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # SSH vào BE-02 và thực hiện deploy
            ssh be-02 '
              cd /srv/app/workspace-backend
              
              # Kiểm tra xem đã có git repo chưa
              if [ ! -d .git ]; then
                # Nếu chưa có git repo, clone mới
                rm -rf ./* 2>/dev/null || true
                rm -rf ./.* 2>/dev/null || true
                git clone https://github.com/Linh3694/workspace-backend.git .
              else
                # Nếu đã có git repo, fetch và reset
                git fetch origin
                git reset --hard origin/main
                git clean -fd
              fi
              
              # Cài đặt dependencies và chạy script
              npm install --production
              node scripts/addEmoji.js
              
              # Reload ứng dụng
              pm2 reload all
            '

      - name: Health Check
        uses: appleboy/ssh-action@master
        with:
          host: 42.96.41.26
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Chờ 30 giây cho các service khởi động
            sleep 30
            
            # Kiểm tra health của BE-01
            BE1_HEALTH=$(ssh be-01 'curl -s -o /dev/null -w "%{http_code}" http://localhost:5001/health')
            
            # Kiểm tra health của BE-02
            BE2_HEALTH=$(ssh be-02 'curl -s -o /dev/null -w "%{http_code}" http://localhost:5001/health')
            
            if [ "$BE1_HEALTH" != "200" ] || [ "$BE2_HEALTH" != "200" ]; then
              echo "Health check failed!"
              echo "BE-01 health status: $BE1_HEALTH"
              echo "BE-02 health status: $BE2_HEALTH"
              exit 1
            fi
            
            echo "Deployment successful! Both backends are healthy." 